template_path: app.yaml
stack_name: synapse-login-scipoolprod
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
depedencies:
  - scipoolprod/synapse-login-scipoolprod-base.yaml
parameters:
  AppDeployBucketName: "org-sagebase-scipoolprod-synapse-login-scipoolprod"
  SnsBounceNotificationEndpoint: "aws.scipoolprod@sagebase.org"
  SnsNotificationEndpoint: "aws.scipoolprod@sagebase.org"
  DNSHostname: "synapse-login-scipoolprod"
  DNSDomain: "scipoolprod.org"
  EC2InstanceType: "t3.small"
  EC2KeyName: 'scipool'
  VpcName: "internalpoolvpc"
  SynapseOauthClientSecret: !ssm /synapse-login-scipoolprod/SynapseOauthClientSecret
  PropertiesFilename: "scipoolprod.properties"
  SolutionStackName: '64bit Amazon Linux 2018.03 v3.3.4 running Tomcat 8.5 Java 8'
  AutoScalingMinSize: "2"
  AutoScalingMaxSize: "3"
