project_code: "sage-bionetworks"
profile: {{ var.profile | default("default") }}
region: {{ var.region | default("us-east-1") }}
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
