template_path: app.yaml
stack_name: synapse-login-scipooldev
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
depedencies:
  - scipooldev/synapse-login-scipooldev-base.yaml
parameters:
  AppDeployBucketName: "org-sagebase-scipooldev-synapse-login-scipooldev"
  SnsBounceNotificationEndpoint: "aws.scipooldev@sagebase.org"
  SnsNotificationEndpoint: "aws.scipooldev@sagebase.org"
  DNSHostname: "synapse-login-scipooldev"
  DNSDomain: "scipooldev.org"
  EC2InstanceType: "t3.small"
  EC2KeyName: 'scipool'
  VpcName: "cesspoolvpc"
  SynapseOauthClientSecret: !ssm /synapse-login-scipooldev/SynapseOauthClientSecret
  PropertiesFilename: "scipooldev.properties"
  SolutionStackName: '64bit Amazon Linux 2018.03 v3.3.4 running Tomcat 8.5 Java 8'
  AutoScalingMinSize: "1"
  AutoScalingMaxSize: "2"
